#!/bin/bash

if [ -z "$GIT_REPO" ]; then
 echo "You need to pass the \$GIT_REPO variable to the container for this to work"
 exit
fi

cd /var/www/html
git pull || exit 1
chown -Rf nginx:nginx /var/www/html

# Try auto install for composer
if [ -f "/var/www/html/composer.lock" ]; then
  composer install --no-dev --working-dir=/var/www/html
fi